version: 1
services:
  - type: web
    name: attendance-app
    env: python
    region: frankfurt  # or your preferred region
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k gevent -w 1 -b 0.0.0.0:$PORT teacher.app:app"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false